[package]
name = "connectioniterator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
closure = "0.3.0"
dyn-clone = "1.0.13"
expect-test = "1.4.1"
